// Zero-Budget Model Advisor -- shared site chrome.
//
// Classic (non-module) script, loaded by every route via <script src="site.js">
// so it works over file:// without the CORS restriction that blocks fetch/XHR
// and ES-module imports from a file:// page (Decision C1 amendment, 2026-09-05).
// This file never imports advisor.js/recommendation.js -- only index.html does
// that, as a module, since only the advisor needs recommend().
//
// Data loading is a SINGLE path: every page reads window.__INDEX_DATA__,
// populated by a classic <script src="data/index.data.js"> tag loaded before
// this one. That file and data/index.json are both generated by
// 04-analysis/build_advisor_index.py in one pass from the same in-memory
// object, so they cannot disagree at generation time -- there is no
// fetch-then-fallback branch here to be wrong in two different ways.
// checkDataFreshness() below is a separate, non-blocking integrity check for
// the case where one of them was edited by hand afterwards.
//
// No framework, no build step. The data-generation step (build_advisor_index.py)
// is not a bundler or toolchain -- it's part of the refresh procedure, run
// whenever scores.json changes, same as regenerating index.json always was.

const SITE = (() => {
  // =======================================================================
  // CONFIGURATION -- two Google Forms, two endpoints, two field maps.
  // Feedback and events are separate forms with separate field sets; there
  // is no single shared endpoint. Google Forms accepts only
  // application/x-www-form-urlencoded or multipart FormData keyed by each
  // question's entry.NNNNNNN id -- it silently discards a JSON body, which
  // is what the previous version of this file sent. Every submit()/track()
  // below still runs and updates the UI identically if either endpoint is
  // ever blanked out; only the network call becomes a no-op.
  // =======================================================================
  const FEEDBACK_ENDPOINT = "https://docs.google.com/forms/d/e/1FAIpQLSdg1bBD3RCQWGFNRQi7TVouOZodAc97ckjFxLvqhx-EdpEEdw/formResponse";
  const FEEDBACK_FIELDS = {
    submission_type: "entry.1427325620",     // reconciled placement/type concept -- see postPayload()
    route: "entry.1635871476",
    session_id: "entry.1488956130",
    index_version: "entry.1057617239",
    client_timestamp: "entry.129907301",
    rating: "entry.1325510675",              // recommendation placement: "useful" / "not_useful"
    changed_decision: "entry.2030450934",    // recommendation placement, up+yn path only: "yes" / "no"
    advisor_inputs: "entry.329003657",       // recommendation: query inputs; persistent: whatever page context was open
    recommendation_shown: "entry.1424419013",
    dispute_target: "entry.1606855644",      // "<model> × <task> × <dimension>"
    dispute_your_score: "entry.855334412",
    free_text: "entry.757908318",            // roadmap folds its two inputs in here -- see mountFooterFeedback
  };

  const EVENTS_ENDPOINT = "https://docs.google.com/forms/d/e/1FAIpQLSco7EU92U9PUKsAvQXm0wLQAmyVfEDwSeDQ5ACrkm86g8fpqA/formResponse";
  const EVENTS_FIELDS = {
    session_id: "entry.1229996310",
    route: "entry.718483950",
    index_version: "entry.1003587934",
    client_timestamp: "entry.484716733",
    events_json: "entry.1630733156",
  };

  const PRIVACY_NOTE =
    'Posted to a Google Form — no account, no PII. <a href="about.html#privacy">Full disclosure.</a>';

  const NAV_ITEMS = [
    { label: "Advisor", href: "index.html", key: "advisor" },
    { label: "Results", href: "results.html", key: "results" },
    { label: "Methodology", href: "methodology.html", key: "methodology" },
    { label: "About", href: "about.html", key: "about" },
  ];

  // "Model profiles" is not one of the five spec'd routes (UX-and-Feedback-Spec
  // S2 lists /, /results, /model/:id, /methodology, /about -- no bare model
  // index). A model profile is reached from a specific model, not a nav item,
  // so it is intentionally absent from NAV_ITEMS rather than linked as a dead
  // placeholder.

  const CALIBRATION = {
    kappa: "0.358",
    summary:
      "Held-out agreement fell to κ=0.358, below this project's own 0.45 floor — " +
      "the calibration gate is invalidated, and every score on this site is published " +
      "anyway, disclosed rather than hidden.",
    detail:
      "The judge's agreement with a careful human, measured on a fresh 20-item set never " +
      "used to tune the prompt, came in at κ=0.358 — below the 0.45 floor this project " +
      "pre-registered as the bar for trusting a judge over hand-scoring everything. The " +
      "in-sample κ=0.650 that first cleared the gate was measured against the same 20 " +
      "items the prompt had been iterated on four times, and didn't hold on unseen cases. " +
      "Read every score on this site as judge output that has not been shown to agree with " +
      "a human above chance-corrected reliability — full account in Methodology.",
  };

  // ---------------------------------------------------------------------
  // Data loading -- one path. See the file header: window.__INDEX_DATA__ is
  // the only thing any page ever renders from.
  // ---------------------------------------------------------------------
  let INDEX_VERSION = null; // data.generated_at, set once loadIndexData() resolves

  async function loadIndexData() {
    if (!window.__INDEX_DATA__) {
      throw new Error(
        "window.__INDEX_DATA__ is not set -- check that data/index.data.js " +
        "is included via <script src> before site.js, and that it was " +
        "generated by 04-analysis/build_advisor_index.py."
      );
    }
    INDEX_VERSION = window.__INDEX_DATA__.generated_at;
    return window.__INDEX_DATA__;
  }

  // ---------------------------------------------------------------------
  // Session ID -- anonymised, client-generated, NOT persisted across visits
  // (UX-and-Feedback-Spec S5). sessionStorage clears when the tab/browser
  // closes, which is exactly that lifetime; localStorage would outlive it
  // and is deliberately not used here.
  // ---------------------------------------------------------------------
  let sessionIdMemo = null;
  function getSessionId() {
    if (sessionIdMemo) return sessionIdMemo;
    try {
      let id = sessionStorage.getItem("zbma_session");
      if (!id) {
        id = (crypto.randomUUID ? crypto.randomUUID() : String(Date.now()) + Math.random().toString(16).slice(2));
        sessionStorage.setItem("zbma_session", id);
      }
      sessionIdMemo = id;
    } catch (e) {
      // sessionStorage unavailable (e.g. private-mode edge case) -- fall back
      // to an id that lives only as long as this page, never persisted.
      sessionIdMemo = String(Date.now()) + Math.random().toString(16).slice(2);
    }
    return sessionIdMemo;
  }

  function currentRoute() {
    return location.pathname.split("/").pop() || "index.html";
  }

  // ---------------------------------------------------------------------
  // Feedback submission -- builds a real Google Forms FormData payload (the
  // form discards anything else, including the JSON body a prior version of
  // this file sent). `submissionType` is the reconciled placement/type
  // concept from the four mount*Feedback() functions below, sent as the
  // form's single submission_type field rather than a parallel one. Every
  // field is optional on the form, so any key the caller doesn't supply
  // goes through as an empty string, not omitted -- Forms has no concept of
  // a partially-shaped submission, only present-or-blank fields. Fires and
  // forgets; a Forms endpoint reached with mode:"no-cors" gives no readable
  // response either way, so there is nothing to await or branch on. No-ops
  // if FEEDBACK_ENDPOINT is unset.
  // ---------------------------------------------------------------------
  function postPayload(submissionType, fields) {
    if (!FEEDBACK_ENDPOINT) return;
    const values = Object.assign({
      submission_type: submissionType,
      route: currentRoute(),
      session_id: getSessionId(),
      index_version: INDEX_VERSION || "",
      client_timestamp: new Date().toISOString(),
      rating: "", changed_decision: "", advisor_inputs: "", recommendation_shown: "",
      dispute_target: "", dispute_your_score: "", free_text: "",
    }, fields);
    const fd = new FormData();
    for (const key in FEEDBACK_FIELDS) fd.append(FEEDBACK_FIELDS[key], String(values[key] != null ? values[key] : ""));
    try {
      if (navigator.sendBeacon) navigator.sendBeacon(FEEDBACK_ENDPOINT, fd);
      else fetch(FEEDBACK_ENDPOINT, { method: "POST", mode: "no-cors", body: fd }).catch(() => {});
    } catch (e) { /* never let a bad endpoint break the page */ }
  }

  // ---------------------------------------------------------------------
  // Event tracking -- first-party, posts to its own Forms endpoint (a
  // second form, not a separate analytics service -- Decision C1's no-
  // backend constraint stands). Same anonymised, non-persisted session id
  // as feedback -- this is the existing privacy stance applied to a second
  // purpose, not a new one. Narrow, named scope only: see the track() call
  // sites in each page for the full list of events.
  //
  // Batched, not per-click: events accumulate in EVENT_QUEUE and flush once,
  // together, on pagehide/visibilitychange rather than one request per
  // event, as a single events_json field (Forms has no repeating-row concept
  // for a single submission, so one batched submission per session is one
  // row with the whole batch inside it, not N rows). sendBeacon (designed
  // for exactly this "fire on unload" case) is used when available, taking
  // a FormData object directly, so a flush never blocks or delays
  // navigation; the fetch fallback uses keepalive for the same reason. If
  // EVENTS_ENDPOINT is unset or the request fails, this fails silently --
  // the site behaves exactly as if tracking were off, per design.
  // ---------------------------------------------------------------------
  const EVENT_QUEUE = [];

  function track(event, props) {
    if (!EVENTS_ENDPOINT) return;
    EVENT_QUEUE.push(Object.assign({
      event,
      timestamp: new Date().toISOString(),
      route: currentRoute(),
    }, props || {}));
  }

  function flushEvents() {
    if (!EVENTS_ENDPOINT || EVENT_QUEUE.length === 0) return;
    const batch = EVENT_QUEUE.splice(0);
    const fd = new FormData();
    fd.append(EVENTS_FIELDS.session_id, getSessionId());
    fd.append(EVENTS_FIELDS.route, currentRoute());
    fd.append(EVENTS_FIELDS.index_version, INDEX_VERSION || "");
    fd.append(EVENTS_FIELDS.client_timestamp, new Date().toISOString());
    fd.append(EVENTS_FIELDS.events_json, JSON.stringify(batch));
    try {
      if (navigator.sendBeacon) navigator.sendBeacon(EVENTS_ENDPOINT, fd);
      else fetch(EVENTS_ENDPOINT, { method: "POST", mode: "no-cors", body: fd, keepalive: true }).catch(() => {});
    } catch (e) { /* never block navigation */ }
  }
  addEventListener("pagehide", flushEvents);
  addEventListener("visibilitychange", () => { if (document.visibilityState === "hidden") flushEvents(); });

  // ---------------------------------------------------------------------
  // Freshness guard -- fire-and-forget, never on the rendering path. Best-
  // effort fetch() of index.json purely to compare generated_at against the
  // mirror already in use. A mismatch means one file was regenerated (or
  // hand-edited) without the other -- exactly the silent-drift failure mode
  // that produced the constraint_conformance/abstention_calibration naming
  // gaps and the hardcoded-ceilings dict before. Silent divergence is the
  // failure; this makes it loud instead. If fetch() can't run at all (e.g.
  // file://), there is nothing to compare against and this simply no-ops --
  // that is not a drift signal, just an absent check.
  // ---------------------------------------------------------------------
  function checkDataFreshness(data) {
    fetch("data/index.json")
      .then((res) => (res.ok ? res.json() : null))
      .then((fresh) => {
        if (fresh && fresh.generated_at !== data.generated_at) {
          const banner = document.createElement("div");
          banner.className = "data-drift-banner";
          banner.textContent =
            "Data integrity check failed: data/index.json (generated " + fresh.generated_at + ") and " +
            "data/index.data.js (generated " + data.generated_at + ") disagree. One was regenerated " +
            "without the other -- re-run 04-analysis/build_advisor_index.py and redeploy.";
          document.body.prepend(banner);
        }
      })
      .catch(() => { /* no fetch path available (e.g. file://) -- nothing to check */ });
  }

  // ---------------------------------------------------------------------
  // Header: nav + the site-wide, persistent, non-dismissible calibration
  // strip (Decision C7 design decision #3; DESIGN-DECISION.md S9). Every
  // route renders this identically except methodology.html, which states
  // outright that the whole page IS the disclosure rather than linking to
  // an expansion of itself (expandable:false).
  // ---------------------------------------------------------------------
  function renderHeader(mountEl, { active, data, expandable = true, trailingNote = "" } = {}) {
    const nav = NAV_ITEMS.map(
      (item) =>
        `<a href="${item.href}"${item.key === active ? ' class="current"' : ""}>${item.label}</a>`
    ).join("\n      ");

    const date = data ? data.judged_at : "—";
    const judge = data ? data.judge_model : "—";
    const version = data ? data.judge_prompt_version : "—";

    const expansion = expandable
      ? `<details>
          <summary class="expand-label"></summary>
          <div class="disclosure-more">${CALIBRATION.detail}</div>
        </details>`
      : "";

    mountEl.innerHTML = `
<header class="masthead">
  <div class="masthead-top">
    <a class="wordmark" href="index.html">Zero-Budget Model Advisor<small>free-tier LLM benchmark &amp; routing advisor</small></a>
    <nav class="routes">
      ${nav}
    </nav>
  </div>
  <div class="disclosure-strip">
    <div class="disclosure-inner">
      <span class="disclosure-mark">κ ${CALIBRATION.kappa}</span>
      <div>
        <p>Measured ${date} · judge <span class="mono">${judge}</span> v${version}. ${CALIBRATION.summary}${trailingNote ? " " + trailingNote : ""}</p>
        ${expansion}
      </div>
    </div>
  </div>
</header>`;
  }

  // ---------------------------------------------------------------------
  // Feedback widget -- four placements now (the three contextual ones below,
  // plus mountPersistentFeedback further down), per UX-and-Feedback-Spec S5
  // and Decision C3 as amended 2026-09-06. No accounts, no PII. Each
  // render*Feedback() function wires real state transitions (idle ->
  // follow-up -> thanks) and actually calls postPayload() with the real
  // Google Forms field set on submit.
  // ---------------------------------------------------------------------

  // Thumb icon: inline SVG, not an emoji glyph -- emoji rendering depends on
  // the OS/browser having a colour-emoji font installed and falls back
  // inconsistently (this is what was actually happening: both buttons render
  // empty on a system without one). An inline path always renders, is
  // themeable with currentColor, and doesn't depend on a font. "Down" reuses
  // the same path, flipped with a CSS transform, rather than a second path.
  const THUMB_SVG =
    '<svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true">' +
    '<path d="M2 11h4v10H2a1 1 0 0 1-1-1v-8a1 1 0 0 1 1-1z"/>' +
    '<path d="M8 21h9.5a2 2 0 0 0 1.94-1.515l1.66-6.63A2 2 0 0 0 19.16 10.5H14l.9-4.32A1.77 1.77 0 0 0 13.16 4c-.4 0-.79.16-1.07.45L8 9v12z"/>' +
    "</svg>";

  // Placement 1: under the recommendation card (index.html). `context` is
  // the advisor inputs that produced the current recommendation (tasks,
  // requestsPerDay, latency, errorCost) plus which model was shown -- this
  // is the "advisor inputs behind the recommendation" field UX S5 names.
  function mountRecommendationFeedback(mountEl, context) {
    mountEl.innerHTML = `
<div class="feedback-widget">
  <div class="feedback-prompt">Was this useful?</div>
  <div class="feedback-thumbs">
    <button class="thumb" type="button" data-thumb="up" aria-label="This was useful" aria-pressed="false">${THUMB_SVG}</button>
    <button class="thumb thumb-down" type="button" data-thumb="down" aria-label="This was not useful" aria-pressed="false">${THUMB_SVG}</button>
  </div>
  <div class="feedback-followup" data-followup="up" hidden>
    <div class="feedback-yn">
      Did this change what you were going to use?
      <button type="button" data-yn="yes" aria-label="Yes, it changed what I was going to use">Yes</button>
      <button type="button" data-yn="no" aria-label="No, it did not change what I was going to use">No</button>
    </div>
  </div>
  <div class="feedback-followup" data-followup="down" hidden>
    <input type="text" placeholder="One line — what would make this better?">
    <button type="button" data-submit="down">Send</button>
  </div>
  <div class="feedback-thanks" hidden>Thanks — logged against this query and index version. No account needed.</div>
  <p class="privacy-note">${PRIVACY_NOTE}</p>
</div>`;

    const up = mountEl.querySelector('[data-thumb="up"]');
    const down = mountEl.querySelector('[data-thumb="down"]');
    const followUp = mountEl.querySelector('[data-followup="up"]');
    const followDown = mountEl.querySelector('[data-followup="down"]');
    const thanks = mountEl.querySelector(".feedback-thanks");
    let picked = null;

    function selectThumb(which) {
      picked = which;
      up.classList.toggle("selected", which === "up");
      up.setAttribute("aria-pressed", String(which === "up"));
      down.classList.toggle("selected", which === "down");
      down.setAttribute("aria-pressed", String(which === "down"));
      followUp.hidden = which !== "up";
      followDown.hidden = which !== "down";
      thanks.hidden = true;
    }
    function submit(extra) {
      const { primary_model, ...advisorInputs } = context || {};
      postPayload("recommendation", Object.assign({
        rating: picked === "up" ? "useful" : "not_useful",
        advisor_inputs: JSON.stringify(advisorInputs),
        recommendation_shown: primary_model || "",
      }, extra));
      track("feedback_complete", { placement: "recommendation" });
      followUp.hidden = true;
      followDown.hidden = true;
      thanks.hidden = false;
    }
    up.addEventListener("click", () => selectThumb("up"));
    down.addEventListener("click", () => selectThumb("down"));
    mountEl.querySelector('[data-yn="yes"]').addEventListener("click", () => submit({ changed_decision: "yes" }));
    mountEl.querySelector('[data-yn="no"]').addEventListener("click", () => submit({ changed_decision: "no" }));
    mountEl.querySelector('[data-submit="down"]').addEventListener("click", () => {
      const text = mountEl.querySelector('.feedback-followup[data-followup="down"] input').value;
      submit({ free_text: text });
    });
  }

  // Placement 2: on an expanded score cell (results.html). Caller supplies
  // the dimension list for the mini-form's <select> plus which model/task
  // cell this is, for the payload. Fires feedback_open on mount, since
  // mounting only happens when a user expands a cell -- that expansion IS
  // the "open" for this placement.
  function mountDisputeForm(mountEl, dimensions, cellContext) {
    track("feedback_open", { placement: "dispute", cell: cellContext });
    mountEl.innerHTML = `
<div class="feedback-inline">
  <div class="feedback-label">Disagree with this score?</div>
  <div class="feedback-row" data-dispute-form>
    <select data-dispute-dim aria-label="Which dimension">${dimensions.map((d) => `<option>${d.replace(/_/g, " ")}</option>`).join("")}</select>
    <input type="number" min="0" max="3" placeholder="your score, 0–3" aria-label="Your score, 0 to 3">
    <input type="text" placeholder="why, one line" aria-label="Why, one line">
    <button type="button" data-dispute-submit>Submit</button>
  </div>
  <div class="feedback-thanks" hidden>Thanks — logged with this cell, your inputs, and the index version. No account needed.</div>
  <p class="privacy-note">${PRIVACY_NOTE}</p>
</div>`;
    const form = mountEl.querySelector("[data-dispute-form]");
    const thanks = mountEl.querySelector(".feedback-thanks");
    mountEl.querySelector("[data-dispute-submit]").addEventListener("click", () => {
      const dimension = mountEl.querySelector("[data-dispute-dim]").value;
      postPayload("dispute", {
        dispute_target: `${cellContext.model} × ${cellContext.task} × ${dimension}`,
        dispute_your_score: mountEl.querySelector('input[type="number"]').value,
        free_text: mountEl.querySelector('input[type="text"]').value,
      });
      track("feedback_complete", { placement: "dispute" });
      form.hidden = true;
      thanks.hidden = false;
    });
  }

  // Placement 3: footer, "what should we measure next?" (results.html, about.html).
  function mountFooterFeedback(mountEl) {
    mountEl.innerHTML = `
<div class="feedback-footer">
  <h2>What should we measure next?</h2>
  <p>Model or task requests feed directly into the next quarterly refresh's scope. No account, no PII.</p>
  <div class="feedback-row" data-footer-form>
    <input type="text" placeholder="A model you'd like benchmarked" aria-label="A model you'd like benchmarked">
    <input type="text" placeholder="A task you'd like covered" aria-label="A task you'd like covered">
    <button type="button" data-footer-submit>Send</button>
  </div>
  <div class="feedback-thanks" hidden>Thanks — logged with this page and the current index version.</div>
  <p class="privacy-note">${PRIVACY_NOTE}</p>
</div>`;
    const form = mountEl.querySelector("[data-footer-form]");
    const thanks = mountEl.querySelector(".feedback-thanks");
    mountEl.querySelector("[data-footer-submit]").addEventListener("click", () => {
      const [modelInput, taskInput] = mountEl.querySelectorAll("input");
      // No dedicated model/task-request fields on the form -- reconciled into
      // the one free_text field rather than inventing parallel ones.
      postPayload("roadmap", { free_text: `Model: ${modelInput.value} | Task: ${taskInput.value}` });
      track("feedback_complete", { placement: "footer" });
      form.hidden = true;
      thanks.hidden = false;
    });
  }

  // ---------------------------------------------------------------------
  // Placement 4: a persistent entry point on every route (Decision C3
  // amendment, 2026-09-06). The three placements above stay primary --
  // this exists because they only catch a reader at three specific moments,
  // and a reader who wants to say something at any OTHER moment previously
  // had no path in at all. It is additive, not a replacement, and it is
  // only compliant with UX-and-Feedback-Spec S5's "moment of judgment, not
  // a generic footer" principle because it always carries real context: a
  // small tab, not a blank box, that pre-fills what the reader is actually
  // looking at. `getContext()` is supplied per page and called fresh each
  // time the panel opens, so it reflects the current lens/cell/query, not
  // whatever was true when the page first loaded.
  // ---------------------------------------------------------------------
  function describeContext(ctx) {
    const parts = [];
    if (ctx.tasks) parts.push(ctx.tasks.join(", ") + " · " + ctx.requestsPerDay + "/day · " + ctx.latency + " · " + ctx.errorCost);
    if (ctx.primary_model) parts.push("recommended " + ctx.primary_model);
    if (ctx.lens) parts.push(ctx.lens + " lens");
    if (ctx.expanded_cell) parts.push(ctx.expanded_cell.model + " × " + ctx.expanded_cell.task);
    if (ctx.model_id) parts.push(ctx.model_id);
    return parts.length ? parts.join(" · ") : "this page, no query yet";
  }

  function mountPersistentFeedback(getContext) {
    const tab = document.createElement("button");
    tab.type = "button";
    tab.className = "persistent-feedback-tab";
    tab.textContent = "Feedback";
    tab.setAttribute("aria-label", "Open feedback about this page");

    const panel = document.createElement("div");
    panel.className = "persistent-feedback-panel";
    panel.hidden = true;
    panel.innerHTML = `
      <div class="persistent-feedback-head">
        <span>Feedback on what you're looking at</span>
        <button type="button" class="persistent-feedback-close" aria-label="Close feedback panel">&times;</button>
      </div>
      <p class="persistent-feedback-context"></p>
      <textarea rows="3" placeholder="What's on your mind?" aria-label="Your feedback"></textarea>
      <button type="button" class="persistent-feedback-submit">Send</button>
      <div class="feedback-thanks" hidden>Thanks — logged with this context. No account needed.</div>
      <p class="privacy-note">${PRIVACY_NOTE}</p>
    `;

    const contextEl = panel.querySelector(".persistent-feedback-context");
    const textarea = panel.querySelector("textarea");
    const submitBtn = panel.querySelector(".persistent-feedback-submit");
    const thanks = panel.querySelector(".feedback-thanks");
    let openContext = {};

    function open() {
      openContext = (getContext ? getContext() : {}) || {};
      contextEl.textContent = "Context: " + describeContext(openContext);
      textarea.value = "";
      textarea.hidden = false;
      submitBtn.hidden = false;
      thanks.hidden = true;
      panel.hidden = false;
      track("feedback_open", { placement: "persistent", context: openContext });
    }
    function close() { panel.hidden = true; }

    tab.addEventListener("click", open);
    panel.querySelector(".persistent-feedback-close").addEventListener("click", close);
    submitBtn.addEventListener("click", () => {
      // advisor_inputs is the closest existing field for "whatever context
      // was attached" -- reconciled here rather than a parallel context field.
      postPayload("persistent", { advisor_inputs: JSON.stringify(openContext), free_text: textarea.value });
      track("feedback_complete", { placement: "persistent" });
      textarea.hidden = true;
      submitBtn.hidden = true;
      thanks.hidden = false;
    });

    document.body.appendChild(tab);
    document.body.appendChild(panel);
  }

  return {
    loadIndexData,
    checkDataFreshness,
    renderHeader,
    mountRecommendationFeedback,
    mountDisputeForm,
    mountFooterFeedback,
    mountPersistentFeedback,
    track,
  };
})();
