"""Flattens 04-analysis/scores.json into 05-site/data/index.json -- only what
the client-side advisor (05-site/advisor/advisor.js) needs, per Decision C1
(static site, client-side advisor over a JSON data file). Drops per-case
detail (case_scores) that belongs to the /results and /model/:id pages, not
the advisor. One responsibility: flatten, don't recompute -- scores.json
remains the source of truth.

Also emits 05-site/data/index.data.js, a `window.__INDEX_DATA__ = {...}`
mirror of the exact same in-memory object, loaded via a classic <script src>
tag. Every route reads that global, never fetch() -- ES-module imports and
fetch() are both blocked when a page is opened via file:// (Decision C1
amendment, 2026-09-05), and a classic script tag is not. Both files are
written from the same `out` object in the same pass, so they cannot diverge
at generation time; site.js's runtime freshness check exists for the case
where one of them is edited by hand afterwards, which this script never does.
"""

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCORES_FILE = ROOT / "04-analysis" / "scores.json"
JSON_OUT_FILE = ROOT / "05-site" / "data" / "index.json"
JS_MIRROR_FILE = ROOT / "05-site" / "data" / "index.data.js"


def flatten_task(task_data):
    return {
        "task_score": task_data["task_score"],
        "adversarial_sub_score": task_data["adversarial_sub_score"],
        "n_na_dimension_marks": task_data["n_na_dimension_marks"],
        "median_spread": task_data["median_spread"],
        "dimension_means": task_data["dimension_means"],
        "benchmark": task_data["benchmark"],
    }


def main():
    with open(SCORES_FILE, encoding="utf-8") as f:
        scores = json.load(f)

    out = {
        "schema_version": "1.0",
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "rubric_version": scores["rubric_version"],
        "judge_model": scores["judge_model"],
        "judge_provider": scores["judge_provider"],
        "judge_prompt_version": scores["judge_prompt_version"],
        "judged_at": scores["judged_at"],
        "scored_models": scores["scored_models"],
        "models": {},
        "excluded": {},
    }

    for model_id in scores["scored_models"]:
        m = scores["models"][model_id]
        out["models"][model_id] = {
            "tasks": {task: flatten_task(t) for task, t in m["tasks"].items()},
            "rate_limit_ceiling": m["rate_limit_ceiling"],
        }

    or_data = scores["openrouter_excluded_from_quality"]
    out["excluded"]["openrouter-gpt-oss-20b"] = {
        "reason": "Decision A5 -- benchmark run returned 96/300 (32%) success, "
                  "insufficient coverage for median-of-three quality scoring.",
        "benchmark_overall": or_data["benchmark_overall"],
        "rate_limit_ceiling": or_data["rate_limit_ceiling"],
    }

    JSON_OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(out, indent=2)

    with open(JSON_OUT_FILE, "w", encoding="utf-8") as f:
        f.write(payload)
    print(f"Wrote {JSON_OUT_FILE}")

    mirror = (
        "// GENERATED by build_advisor_index.py -- do not hand-edit.\n"
        "// Emitted in the same pass as index.json, from the same in-memory\n"
        "// object, so the two cannot disagree at generation time. Exists only\n"
        "// because file:// blocks both ES-module imports and fetch() -- a\n"
        "// classic <script src> tag is exempt from both restrictions.\n"
        f"window.__INDEX_DATA__ = {payload};\n"
    )
    with open(JS_MIRROR_FILE, "w", encoding="utf-8") as f:
        f.write(mirror)
    print(f"Wrote {JS_MIRROR_FILE}")


if __name__ == "__main__":
    main()
